# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '29thAssignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AutoLayout
  pod 'SnapKit'
  pod 'Then'

  # Pods for Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  # Pods for Network
  pod 'Alamofire', '~> 5.4'
  pod 'Moya', '~> 14.0'
end
