# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '29thSeminar4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 29thSeminar4

  target '29thSeminar4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '29thSeminar4UITests' do
    # Pods for testing
  end

  # Pods for Networking
  pod 'Alamofire'
end
